### ISSUE TITLE
Make `foldrDefault`/`foldlDefault` stack-safe

### ISSUE THREAD

**Issue by ntwilson** [purescript/purescript-foldable-traversable#148]
Currently, `foldrDefault` and `foldlDefault` are not stack-safe, even when given a stack-safe `foldMap` implementation. @natefaubion proposes a stack-safe implementation strategy for these functions [here](https://discourse.purescript.org/t/stack-safe-default-foldr/2974/2).  Would you accept a pull request to make `foldrDefault` and `foldlDefault` stack-safe using this strategy?  This would almost certainly make the implementation slower than the current implementation, but remain _O(n)_.

**Comment by natefaubion** [comment]
> This would almost certainly make the implementation slower than the current implementation

FWIW, I don't think this is a given since it's already accumulating a separate data structure with `Endo`.

**Comment by JordanMartinez** [comment]
> This would almost certainly make the implementation slower than the current implementation

Can we get some benchmarks to confirm/deny that claim?

**Comment by ntwilson** [comment]
Yes - if it's a bit ugly.
https://github.com/ntwilson/purescript-foldable-traversable/tree/benchmarks-for-stack-safe-folds
I've hijacked `main` in the test project to just run benchmarks.  So you can run it with just `npm test`.  Also, it's using a 0.14 compiler because I couldn't figure out how to get setup with 0.15.  Not sure if anything in 0.15 would adjust the times.

**Comment by natefaubion** [comment]
One suggestion is you can get rid of uncons/unsnoc, and inline it into the foldl/foldr instance. This has a significant effect on the larger folds.

```purescript
instance Foldable FreeMonoidTree where
  foldl fn = (\a b -> go a b Empty)
    where
    go acc Empty Empty = acc
    go acc Empty rhs = go acc rhs Empty
    go acc (Node a) rhs = go (fn acc a) rhs Empty
    go acc (Append xs Empty) rhs = go acc xs rhs
    go acc (Append xs ys) Empty = go acc xs ys
    go acc (Append xs ys) rhs = go acc xs $ Append ys rhs
  ...
```

**Comment by natefaubion** [comment]
Additionally, for a modest boost you can put common branches first (Empty is probably uncommon compared to Node/Append):
```purescript
instance Foldable FreeMonoidTree where
  foldl fn = (\a b -> go a b Empty)
    where
    go acc lhs rhs = case lhs of
      Node a ->
        go (fn acc a) rhs Empty
      Append xs ys ->
        case ys of
          Empty ->
            go acc xs rhs
          _ ->
            case rhs of
              Empty ->
                go acc xs ys
              _ ->
                go acc xs (Append ys rhs)
      Empty ->
        case rhs of
          Empty ->
            acc
          _ ->
            go acc rhs Empty
```

**Comment by natefaubion** [comment]
In my tests, this version is around 3-5x faster than the old, unsafe version.
