### ISSUE TITLE
Functor <= Foldable?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-foldable-traversable#16]

**Comment by garyb** [comment]
I think there's a reason why `Functor` is a superclass of `Traversable` rather than `Foldable`, but I can't remember what it was now.

**Comment by joneshf** [comment]
`Foldable` is lawless and too weak to subsume `Functor`. Can't say anything about what should happen with instances based on the functions it has.

**Comment by paf31** [comment]
What about `fold <<< map f = f <<< fold` for any monoid homomorphism `f`?

**Comment by LiamGoodacre** [comment]
Which should also be the same as `foldMap`
~~~idris
foldMap f = fold <<< map f
fold <<< map f = f <<< fold
~~~

**Comment by garyb** [comment]
:+1:

**Comment by garyb** [comment]
I've just found a reasonably good case of why maybe we wouldn't want to do this: we wouldn't be able to have a `Foldable` `Set` anymore, as `Set` is not a functor.

**Comment by LiamGoodacre** [comment]
Are there any types that can't have a `Traversable` instance but do have `Foldable` and `Functor` instances?

**Comment by paf31** [comment]
I'm still on the fence about `Set`. I think it depends what you consider `Set` to represent as an abstract data type. If it represents an _unordered collection without duplicates_, then the `Foldable` instance cannot use the ordering and it's not `Foldable` since you'd need `Ord` for the result type. Something like `toList` wouldn't even be a valid function.

It's definitely convenient for `Set` to be `Foldable` though.

**Comment by garyb** [comment]
There's another example here: http://stackoverflow.com/questions/8359115/haskell-an-example-of-a-foldable-which-is-not-a-functor-or-not-traversable (invariant functors are foldable too)

**Comment by LiamGoodacre** [comment]
Is there any further discussion to be had here, or should we close this?

**Comment by garyb** [comment]
I vote close.
