### ISSUE TITLE
Update dependencies after new release

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-foldable-traversable#18]
Toposorted with transitive dependencies included:

- [ ] purescript-foreign
- [ ] purescript-quickcheck
- [ ] purescript-arb-instances
- [ ] purescript-maps
- [ ] purescript-sets
- [ ] purescript-const
- [ ] purescript-bifunctors
- [ ] purescript-identity
- [ ] purescript-distributive
- [ ] purescript-lens
- [ ] purescript-transformers
- [ ] purescript-lazy
- [ ] purescript-lists
- [ ] purescript-channels
- [ ] purescript-generics
- [ ] purescript-drawing
- [ ] purescript-coproducts
- [ ] purescript-inject
- [ ] purescript-tailrec
- [ ] purescript-free
- [ ] purescript-angular
- [ ] purescript-strongcheck
- [ ] purescript-argonaut
- [ ] purescript-base
- [ ] purescript-graphs
- [ ] purescript-jquery
- [ ] purescript-handlebars
- [ ] purescript-monad-eff
- [ ] purescript-mongodbf
- [ ] purescript-node-fs
- [ ] purescript-parallel
- [ ] purescript-parsing
- [ ] purescript-pattern-arrows
- [ ] purescript-sammy
- [ ] purescript-task
- [ ] purescript-streams
- [ ] purescript-string-parsers
- [ ] purescript-yargs

**Comment by paf31** [comment]
I think we need to start automating this :)

**Comment by garyb** [comment]
Yeah, no kidding!

**Comment by paf31** [comment]
I guess it shouldn't be _that_ difficult to automate it using the GitHub API, at least for the core and contrib libraries. Or even using `git` and `sed` on the command line :)

**Comment by garyb** [comment]
Yeah, the API is pretty good, that's how I generate this stuff in the first place. I guess we'd want to do a dry run of all the changes locally first to discover what needs fixing, and then batch-send-and-release the lot once everything is working together.

**Comment by paf31** [comment]
Well we have the `core-tests` script in the compiler repo, that would at least help us to verify that the dry-run worked.

**Comment by garyb** [comment]
I'll perhaps take a stab at doing something for this at the weekend then.

**Comment by paf31** [comment]
Actually, `bower version minor` will bump the minor version in the file and commit things to Git, so maybe this could all be done on the command line using `bower` and `git`?
