### ISSUE TITLE
Thoughts on `contains`

### ISSUE THREAD

**Issue by alexchandel** [purescript/purescript-foldable-traversable#20]
Essentially a shim for `(flip elem)`. It makes sorting a little prettier:
```purescript
["a", "b", "c"] # filter (flip elem ["a", "b"]) # fold
["a", "b", "c"] # filter (`elem` ["a", "b"]) # fold
["a", "b", "c"] # filter (contains ["a", "b"]) # fold
```

Compare to existing shims like `notElem` vs `(\a (a # flip elem) >>> not)`.

**Comment by garyb** [comment]
We tend not to provide flipped versions of functions unless they're operators (as they can't be flipped with backticks).

``` purescript
fold $ filter (`elem` ["a", "b"]) ["a", "b", "c"]
-- or:
fold <<< filter (`elem` ["a", "b"]) $ ["a", "b", "c"]
```
Would be the idiomatic Haskell (and PureScript IMO) for this. Aside from the `#` usage, I just mean the ```(`elem` xs)``` style is what I'd consider the usual way to do this.

Also, I'm not sure what you're doing in that `notElem` example! ;)

``` purescript
(\x -> not <<< elem x)
```

**Comment by alexchandel** [comment]
Ah ok. And that example was my struggle to compose `elem` into `not`, since `elem :: a -> f a -> Boolean`. Is there a way to compose a function with arbitrarily many arguments into another, like `x :: (a -> b -> c -> d -> e) >>> y :: (e -> f) = z :: (a -> b -> c -> d -> f)` ?

**Comment by joneshf** [comment]
You can use lenses for that.
Or easier than that you could use semantic editor combinators. (which reminds me...)
Or even easier, just compose function composition.

**Comment by hdgarrood** [comment]
Can we close this? Using `elem` with backticks solves the original problem, I think.

**Comment by paf31** [comment]
Agreed.
