### ISSUE TITLE
Function defaults for foldable

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript-foldable-traversable#27]
`foldr`, `foldl` and `foldMap` can be computed in terms of each other by use of `Endo` and `Dual`.
What do people think about providing implementations of these to be used as such:

~~~purescript
instance foldableId :: Foldable Id where
  foldMap f (Id v) = f v
  foldr f m = foldrDefault f m
  foldl f m = foldlDefault f m
~~~

At least until we have default implementations as part of class definitions :) - or should we just wait till we can do that instead?

See default implementations of [Haskell's Foldable](http://haddocks.fpcomplete.com/fp/7.8/20140916-162/base/src/Data-Foldable.html#Foldable)

**Comment by garyb** [comment]
Sounds good to me :+1:

**Comment by LiamGoodacre** [comment]
Great - I'm going to have a go at this once purescript 0.7 RC is out

**Comment by garyb** [comment]
Great, thanks! You can get what is mostly going to be the RC now if you use what's in `master` of `purescript`. It shouldn't be long before we produce the RC for real though.
