### ISSUE TITLE
Dependency on purescript-control not listed in bower.json

### ISSUE THREAD

**Issue by jplatte** [purescript/purescript-foldable-traversable#33]
Used [here](https://github.com/purescript/purescript-foldable-traversable/blob/master/src/Data/Foldable.purs#L23).

**Comment by LiamGoodacre** [comment]
`purescript-control` is pulled in by `purescript-bifunctors` (and also by `purescript-monoid` which itself is pulled in by `purescript-maybe`)

I talked to @paf31 recently about something similar and the conclusion was that it is totally fine to use dependencies of dependencies.  Just letting `bower` sort out what you need and if something complains then add it explicitly.

**Comment by garyb** [comment]
Yup! Relying on transient dependencies are fine, removing a dependency is considered a breaking change.

**Comment by jplatte** [comment]
Alright. I think I got an error message because it didn't get pulled in before, that's why I opened this issue. But I can't reproduce it now, so nvm.
