### ISSUE TITLE
add asum function

### ISSUE THREAD

**Issue by cdepillabout** [purescript/purescript-foldable-traversable#35]
It would be nice to have the [`asum`](https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Foldable.html#v:asum) function defined in this package.

**Comment by hdgarrood** [comment]
I guess, if we were to do this, our version should have the type `(Foldable f, Plus g) => f (g a) -> g a`. However, in that case, `asum` wouldn't be the best name for it, as the `a` in `asum` presumably comes from `Alternative` - the Haskell version does have an `Alternative` constraint. `psum`? `foldPlus`?

**Comment by paf31** [comment]
I like the names `oneOf` or `choose` for this function.
