### ISSUE TITLE
Deprecate either `mconcat` or `fold`?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-foldable-traversable#41]
As far as I can tell, they're identical. At least, assuming you have a law-abiding Foldable instance (which should be a safe assumption).

If we deprecate one, I'd rather it were `mconcat`, but I don't feel strongly either way.

**Comment by paf31** [comment]
I'd also like to deprecate `mconcat`.

**Comment by LiamGoodacre** [comment]
:+1:

**Comment by zudov** [comment]
:+1: for deprecating `mconcat` and only leaving `fold`
