### ISSUE TITLE
Add missing Traversable instances for Bifunctor kit?

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript-foldable-traversable#67]
E.g `Flip` currently has a `Bitraversable` instance but not a `Traversable` instance.

**Comment by garyb** [comment]
Sounds good to me!

**Comment by LiamGoodacre** [comment]
Can't actually add `Bifoldable p => Foldable (Flip p b)`, we'd get a import cycle 😄 
But I'm currently adding the others.

I'm wondering if we could/should reverse the dependency and have bifunctors depend on foldable-traversable instead?

**Comment by LiamGoodacre** [comment]
Completed by #56
