### ISSUE TITLE
Make `foldr` lazy

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-foldable-traversable#69]
`foldrLazy` was recently added to `Data.List`. A somewhat controversial proposal, but maybe we should make `foldr` lazy by default. I liken a strict `foldr` in PureScript to lazy `foldl` in Haskell. Lazy `foldl` almost always uses more memory than you want, and a strict `foldr` almost always does more work than you want.

**Comment by paf31** [comment]
👍

**Comment by natefaubion** [comment]
Note, this would obviously break symmetry, since you can't just do `foldl (+)` and `foldr (+)`. But lack of a lazy Foldable is a real problem, so it may be worth it.

**Comment by natefaubion** [comment]
Another options is to add `foldrLazy` as an additional member of the class, and provide a `foldrDefault` implemented in terms of `foldrLazy`?

**Comment by paf31** [comment]
Adding `foldrLazy` sounds like a fine option to me.

**Comment by hdgarrood** [comment]
Adding `foldrLazy` to `Foldable` sounds sensible to me too. Adding a member to a type class is of course a breaking change, so should we consider adding `foldrLazy` to `Foldable` now, as part of the v0.14.0 changes?

**Comment by JordanMartinez** [comment]
Sure. Seems like many people are in agreement with this. Do you foresee a possibility of removing it in the future?

**Comment by hdgarrood** [comment]
I don't think so, I wouldn't be suggesting adding it otherwise. I'd like to hear from @natefaubion first though, since it's been a few years since the last update. Do you still think the lack of a lazy member in the Foldable class is a problem?

**Comment by natefaubion** [comment]
I think breaking the whole ecosystem is probably not something I would want to do. My experience around foldrLazy is that the overhead is so high, I still wouldn't want to using something like a generic `find` implemented in that way. For example, `Array.findIndex` vs the equivalent implemented with foldrLazy was something like 50x slower with foldrLazy. Way too much allocation overhead, and you'd still have stack issues when forcing it. It's conceptually nice, but all the other constraints make it largely unusable. I would rather have standard set of specialized implementations in all the libraries, and not re-export Foldable functions.

**Comment by garyb** [comment]
Agreed! Shall we close in that case?

**Comment by hdgarrood** [comment]
Works for me. Thanks!
