### ISSUE TITLE
Default implementations of folds in terms of indexed folds

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-foldable-traversable#87]
make sense?

**Comment by hdgarrood** [comment]
not really; can you provide a bit more context?

**Comment by matthewleon** [comment]
in `Foldable.Indexed`:

`foldlDefault f = foldlWithIndex (const f)`.

So if you implement `foldlWithIndex` for, say, `Map`, you then set `foldl = foldlDefault`.

It's what I did here: https://github.com/purescript/purescript-maps/pull/137/commits/8090ce485dfe2673d5f73cdc6451a71cce2ad805

**Comment by matthewleon** [comment]
You could to the same for `Functor`
