### ISSUE TITLE
instances for Lazy

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-foldable-traversable#94]
There should be instances for these classes for the `Lazy` data type from `purescript-lazy`.

**Comment by matthewleon** [comment]
Realizing this is far easier said than done due to the kinds involved.

**Comment by hdgarrood** [comment]
How so? `Lazy` has kind `Type -> Type`, and `Foldable` and `Traversable` both expect something of kind `Type -> Type`, no?

**Comment by matthewleon** [comment]
Well, you can't do, say, `Foldable a => Foldable (Lazy a)`, which is the most natural way of expressing an instance that comes to mind. You'd need some kind of higher-order `Lazy` that does something like `(Type -> Type) -> (Type -> Type)`.

Good chance I'm missing something obvious here, though. Let me know.

**Comment by hdgarrood** [comment]
Oh, I thought you were imagining an instance which would give you e.g. `toList = pure <<< force`.

**Comment by matthewleon** [comment]
Interesting. There is that. I'll give it a shot.

**Comment by matthewleon** [comment]
I'm not really seeing that instance... How it would work, or what it's benefit would be.

**Comment by matthewleon** [comment]
On the other hand... Why not?

**Comment by hdgarrood** [comment]
Yeah, I haven't really used the data type `Lazy` very much so I can't comment on its benefit. I think it can be defined as follows though:
```purescript
instance Foldable Lazy where
  foldr f z x = f (force x) z
  foldl f z x = f z (force x)
  foldMap f = f (force x)
```

**Comment by LiamGoodacre** [comment]
I'm thinking that these instances might be better off in `purescript-lazy`.  Thoughts?

**Comment by matthewleon** [comment]
> I'm thinking that these instances might be better off in purescript-lazy. Thoughts?

That makes sense to me.
