### ISSUE TITLE
Unfoldable1

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-foldable-traversable#99]
Would be nice to have this for the various non-empty types. It would allow, for example, `purescript-gen` to generate arbitrary non-empty types without resorting to potentially expensive `cons`-style operations.

**Comment by garyb** [comment]
I think you mean `Unfoldable1`? We do already have `Foldable1` and `Traversable1`, but you can only consume types with those (`NonEmptyArray`, `NonEmptyList`, etc. have those instances too).

**Comment by matthewleon** [comment]
> I think you mean Unfoldable1?

Yes. Things that happen when you are working too quickly.

**Comment by garyb** [comment]
Actually, you already opened this :smile: - https://github.com/purescript/purescript-unfoldable/issues/19
